-- ───────────────────────────────────────────────
-- Extensions
-- ───────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- for gen_random_uuid()

-- ───────────────────────────────────────────────
-- doctor_rolls
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.doctor_rolls (
    roll_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roll_name  TEXT NOT NULL UNIQUE
        CHECK (roll_name IN ('admin', 'senior', 'junior', 'viewer'))
);

INSERT INTO public.doctor_rolls (roll_name)
VALUES ('admin'), ('senior'), ('junior'), ('viewer')
ON CONFLICT (roll_name) DO NOTHING;

-- ───────────────────────────────────────────────
-- doctor_user
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.doctor_user (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    doctor_id    SERIAL NOT NULL UNIQUE,
    rank_name    TEXT,
    first_name   TEXT,
    last_name    TEXT,
    org_name     TEXT,
    org_id       INT NOT NULL,
    reg_no       TEXT UNIQUE NOT NULL,
    position     TEXT,
    birth_date   DATE,
    gender       TEXT,
    doctor_roll    INT NOT NULL REFERENCES public.doctor_rolls(roll_id)
                   ON UPDATE CASCADE ON DELETE SET NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    password_hash TEXT NOT NULL,
    is_active    BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT chk_doctor_roll CHECK (doctor_roll IS NULL OR doctor_roll IN (1,2,3,4))
);

-- ───────────────────────────────────────────────
-- customer_user
-- ───────────────────────────────────────────────L
CREATE TABLE IF NOT EXISTS public.customer_user (
    "ID"        INT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name  TEXT,
    last_name   TEXT,
    reg_num     TEXT,
    rank_name   TEXT,
    birth_date  DATE,
    gender      INT NOT NULL DEFAULT 0 CHECK (gender IN (0,1)),
    disease_report_id INT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ───────────────────────────────────────────────
-- disease_list
-- ───────────────────────────────────────────────
-- disease_list (FK → doctor_user.doctor_id)
CREATE TABLE IF NOT EXISTS public.disease_list (
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_name         TEXT NOT NULL UNIQUE,
    text_name         TEXT,
    created_doc_id    INT,
    created_org_id    INT,
    created_doctor_id INT,          -- << FK column
    disease_section   TEXT,
    CONSTRAINT fk_disease_created_doctor
      FOREIGN KEY (created_doctor_id)
      REFERENCES public.doctor_user(doctor_id)
      ON UPDATE CASCADE
      ON DELETE SET NULL
);

ALTER TABLE public.customer_user
ADD CONSTRAINT fk_customer_disease_report
FOREIGN KEY (disease_report_id)
REFERENCES public.disease_list(id)
ON UPDATE CASCADE ON DELETE SET NULL;

-- ───────────────────────────────────────────────
-- equipment_types
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.equipment_types (
    type_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name  TEXT NOT NULL
);

-- ───────────────────────────────────────────────
-- hospital_equipment
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.hospital_equipment (
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixed_id          INT,
    name              TEXT,
    count             INT,
    created_date      TIMESTAMPTZ,
    each_price        NUMERIC,
    serial_no         TEXT,
    purchase_date     DATE,
    equipment_type_id INT REFERENCES public.equipment_types(type_id)
                      ON UPDATE CASCADE ON DELETE SET NULL,
    org_id            UUID,
    org_name          TEXT,
    report_id         INT UNIQUE,
    is_active         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_hosp_eq_type ON public.hospital_equipment (equipment_type_id);
CREATE INDEX IF NOT EXISTS idx_hosp_eq_org_id ON public.hospital_equipment (org_id);

-- ───────────────────────────────────────────────
-- equipment_reports
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.equipment_reports (
    report_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id INT NOT NULL REFERENCES public.hospital_equipment(id)
                 ON UPDATE CASCADE ON DELETE CASCADE,
    issue_description TEXT,
    reason       TEXT,
    broken_date  DATE,
    fixed_date   DATE,
    status       TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.hospital_equipment
ADD CONSTRAINT fk_equipment_report
FOREIGN KEY (report_id)
REFERENCES public.equipment_reports(report_id)
ON UPDATE CASCADE ON DELETE SET NULL;

-- ───────────────────────────────────────────────
-- customer_report
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.customer_report (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_serial INT NOT NULL REFERENCES public.customer_user("ID")
                    ON UPDATE CASCADE ON DELETE CASCADE,
    disease_code    TEXT NOT NULL REFERENCES public.disease_list(code_name)
                    ON UPDATE CASCADE ON DELETE RESTRICT,
    created_date    TIMESTAMPTZ,
    end_date        TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_customer_report_user ON public.customer_report (customer_serial);
CREATE INDEX IF NOT EXISTS idx_customer_report_disease ON public.customer_report (disease_code);

-- ───────────────────────────────────────────────
-- (Optional) Seed data for testing
-- ───────────────────────────────────────────────
-- INSERT INTO public.equipment_types (type_name) VALUES ('X-Ray'), ('MRI'), ('ECG') ON CONFLICT DO NOTHING;
-- INSERT INTO public.disease_list (code_name, text_name, disease_section)
-- VALUES ('A01', 'Typhoid fever', 'Infectious diseases')
-- ON CONFLICT DO NOTHING;


-- Refresh tokens (rotation + revoke)
CREATE TABLE IF NOT EXISTS public.refresh_tokens (
    id BIGSERIAL PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.doctor_user(id) ON DELETE CASCADE,
    jti TEXT UNIQUE NOT NULL,
    token_hash TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);



-- (Хүсвэл зөвхөн бодит өөрчлөлт орсон үед л шинэчлэх хувилбар)
 CREATE OR REPLACE FUNCTION public.set_updated_at_if_changed()
 RETURNS TRIGGER AS $$
 BEGIN
   IF (to_jsonb(NEW) - 'updated_at') IS DISTINCT FROM (to_jsonb(OLD) - 'updated_at') THEN
     NEW.updated_at := NOW();
   END IF;
   RETURN NEW;
 END;
 $$ LANGUAGE plpgsql;

-- 2) Триггерүүд: updated_at баганатай хүснэгтүүдэд холбож байна
DROP TRIGGER IF EXISTS trg_doctor_user_updated_at ON public.doctor_user;
CREATE TRIGGER trg_doctor_user_updated_at
BEFORE UPDATE ON public.doctor_user
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_if_changed();

DROP TRIGGER IF EXISTS trg_customer_user_updated_at ON public.customer_user;
CREATE TRIGGER trg_customer_user_updated_at
BEFORE UPDATE ON public.customer_user
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_if_changed();

DROP TRIGGER IF EXISTS trg_hospital_equipment_updated_at ON public.hospital_equipment;
CREATE TRIGGER trg_hospital_equipment_updated_at
BEFORE UPDATE ON public.hospital_equipment
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_if_changed();

DROP TRIGGER IF EXISTS trg_equipment_reports_updated_at ON public.equipment_reports;
CREATE TRIGGER trg_equipment_reports_updated_at
BEFORE UPDATE ON public.equipment_reports
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_if_changed();

DROP TRIGGER IF EXISTS trg_customer_report_updated_at ON public.customer_report;
CREATE TRIGGER trg_customer_report_updated_at
BEFORE UPDATE ON public.customer_report
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_if_changed();