-- ───────────────────────────────────────────────
-- Extensions & search_path
-- ───────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- for gen_random_uuid()

DO $$
BEGIN
  PERFORM set_config('search_path','public',false);
EXCEPTION WHEN others THEN
  -- ignore if lacking permission
END$$;

-- ───────────────────────────────────────────────
-- doctor_rolls (lookup)
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.doctor_rolls (
    roll_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roll_name TEXT NOT NULL UNIQUE
      CHECK (roll_name IN ('admin','senior','junior','viewer'))
);

INSERT INTO public.doctor_rolls (roll_name)
VALUES ('admin'),('senior'),('junior'),('viewer')
ON CONFLICT (roll_name) DO NOTHING;

-- ───────────────────────────────────────────────
-- prev_type (lookup)  бүрэн/хэсэгчилсэн/давтан
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.prev_type (
    type_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name TEXT NOT NULL UNIQUE
);

INSERT INTO public.prev_type (type_name)
VALUES ('бүрэн'), ('хэсэгчилсэн'), ('давтан')
ON CONFLICT (type_name) DO NOTHING;

-- ───────────────────────────────────────────────
-- disease_type (lookup)  архаг/хурц/халдварт  (одоогоор FK үүсгээгүй)
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.disease_type (
    disease_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disease_name TEXT NOT NULL UNIQUE
);

INSERT INTO public.disease_type (disease_name)
VALUES ('архаг'), ('хурц'), ('халдварт')
ON CONFLICT (disease_name) DO NOTHING;

-- ───────────────────────────────────────────────
-- equipment_types (lookup)  + seed
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.equipment_types (
    type_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name TEXT NOT NULL
);

ALTER TABLE public.equipment_types
  ADD CONSTRAINT uq_equipment_type_name UNIQUE (type_name);

INSERT INTO public.equipment_types (type_name)
VALUES
  ('Амбулатори'),
  ('Больниц'),
  ('Халдвар'),
  ('Яаралтай тусламжийн багаж тоног төхөөрөмж'),
  ('Эмийн бус эмчилгээний кабинет'),
  ('Хилийн заставын ариун цэврийн зааварлагчийн багаж, тоног төхөөрөмж')
ON CONFLICT (type_name) DO NOTHING;

-- ───────────────────────────────────────────────
-- doctor_user
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.doctor_user (
    id            UUID  PRIMARY KEY DEFAULT gen_random_uuid(),
    doctor_id     SERIAL NOT NULL UNIQUE,        -- INT, FK target
    rank_name     TEXT,
    first_name    TEXT,
    last_name     TEXT,
    org_name      TEXT,
    org_id        INT  NOT NULL,                 -- таны сонголтоор INT хэвээр
    reg_no        TEXT NOT NULL UNIQUE,
    position      TEXT,
    birth_date    DATE,
    gender        TEXT,
    doctor_roll   INT  NOT NULL
                  REFERENCES public.doctor_rolls(roll_id)
                  ON UPDATE CASCADE ON DELETE RESTRICT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    password_hash TEXT NOT NULL,
    is_active     BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT chk_doctor_roll CHECK (doctor_roll IN (1,2,3,4))
);

-- ───────────────────────────────────────────────
-- hospital_equipment
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.hospital_equipment (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixed_id          INT,
    name              TEXT,
    count             INT,
    created_date      TIMESTAMPTZ,
    each_price        NUMERIC,
    serial_no         TEXT,
    purchase_date     DATE,
    equipment_type_id INT REFERENCES public.equipment_types(type_id)
                      ON UPDATE CASCADE ON DELETE SET NULL,
    org_id            INT,
    report_id         BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE, -- latest report pointer key
    is_active         BOOLEAN NOT NULL DEFAULT TRUE,
    created_doc_id    BIGINT
                      REFERENCES public.doctor_user(doctor_id)
                      ON UPDATE CASCADE ON DELETE SET NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_hosp_eq_type   ON public.hospital_equipment (equipment_type_id);
CREATE INDEX IF NOT EXISTS idx_hosp_eq_org_id ON public.hospital_equipment (org_id);
CREATE INDEX IF NOT EXISTS idx_hosp_eq_doc_id ON public.hospital_equipment (created_doc_id);

-- ───────────────────────────────────────────────
-- equipment_reports  (FK by hospital_equipment.report_id)
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.equipment_reports (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- row id
    report_id         BIGINT NOT NULL
                      REFERENCES public.hospital_equipment(report_id)
                      ON UPDATE CASCADE ON DELETE CASCADE,
    issue_description TEXT,
    reason            TEXT,
    broken_date       DATE,
    fixed_date        DATE,
    status            TEXT,
    created_org_id    INT,
    created_doctor_id BIGINT
                      REFERENCES public.doctor_user(doctor_id)
                      ON UPDATE CASCADE ON DELETE SET NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_equipment_reports_report_id ON public.equipment_reports (report_id);
CREATE INDEX IF NOT EXISTS idx_equipment_reports_doctor    ON public.equipment_reports (created_doctor_id);

-- ───────────────────────────────────────────────
-- customer_user
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.customer_user (
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name         TEXT,
    last_name          TEXT,
    reg_num            TEXT,
    rank_name          TEXT,
    birth_date         DATE,
    gender             INT NOT NULL DEFAULT 0 CHECK (gender IN (0,1)),
    disease_report_id  BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    created_doc_id     INT
                       REFERENCES public.doctor_user(doctor_id)
                       ON UPDATE CASCADE ON DELETE SET NULL,
    created_org_id     INT,
    hospital_id        BIGINT
                       REFERENCES public.hospital_equipment(id)
                       ON UPDATE CASCADE ON DELETE SET NULL,
    org_id             INT,   -- энгийн INT (FK биш)
    dep_name           TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ───────────────────────────────────────────────
-- disease_list  (FK → doctor_user.doctor_id)
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.disease_list (
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_name         TEXT NOT NULL UNIQUE,
    text_name         TEXT,
    created_doc_id    INT,
    created_org_id    INT,
    created_doctor_id INT,
    disease_section   TEXT,
    CONSTRAINT fk_disease_created_doctor
      FOREIGN KEY (created_doctor_id)
      REFERENCES public.doctor_user(doctor_id)
      ON UPDATE CASCADE ON DELETE SET NULL
);

-- customer_user → disease_list FK (disease_report_id points to disease_list.id)
ALTER TABLE public.customer_user
  ADD CONSTRAINT fk_customer_disease_report
  FOREIGN KEY (disease_report_id)
  REFERENCES public.disease_list(id)
  ON UPDATE CASCADE ON DELETE SET NULL;

-- ───────────────────────────────────────────────
-- customer_prev_report (history/timeline)
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.customer_prev_report (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_serial  BIGINT NOT NULL
                     REFERENCES public.customer_user(disease_report_id)
                     ON UPDATE CASCADE ON DELETE CASCADE,
    prev_type        INT NOT NULL
                     REFERENCES public.prev_type(type_id)
                     ON UPDATE CASCADE ON DELETE RESTRICT,
    disease_code     TEXT NOT NULL
                     REFERENCES public.disease_list(code_name)
                     ON UPDATE CASCADE ON DELETE RESTRICT,
    refer            TEXT,
    refer_doc        TEXT,
    refer_org        TEXT,
    refer_date       DATE,
    created_date     TIMESTAMPTZ,
    end_date         TIMESTAMPTZ,

    -- Шинэ нэмэлт багана
    medical_vision   BOOLEAN NOT NULL DEFAULT FALSE
);


CREATE INDEX IF NOT EXISTS idx_customer_prev_report_user
  ON public.customer_prev_report (customer_serial);
CREATE INDEX IF NOT EXISTS idx_customer_prev_report_disease
  ON public.customer_prev_report (disease_code);

-- ───────────────────────────────────────────────
-- updated_at trigger function + triggers
-- ───────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.set_updated_at_if_changed()
RETURNS TRIGGER AS $func$
BEGIN
  IF (to_jsonb(NEW) - 'updated_at') IS DISTINCT FROM (to_jsonb(OLD) - 'updated_at') THEN
    NEW.updated_at := NOW();
  END IF;
  RETURN NEW;
END;
$func$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_doctor_user_updated_at ON public.doctor_user;
CREATE TRIGGER trg_doctor_user_updated_at
BEFORE UPDATE ON public.doctor_user
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_if_changed();

DROP TRIGGER IF EXISTS trg_customer_user_updated_at ON public.customer_user;
CREATE TRIGGER trg_customer_user_updated_at
BEFORE UPDATE ON public.customer_user
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_if_changed();

DROP TRIGGER IF EXISTS trg_hospital_equipment_updated_at ON public.hospital_equipment;
CREATE TRIGGER trg_hospital_equipment_updated_at
BEFORE UPDATE ON public.hospital_equipment
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_if_changed();

DROP TRIGGER IF EXISTS trg_equipment_reports_updated_at ON public.equipment_reports;
CREATE TRIGGER trg_equipment_reports_updated_at
BEFORE UPDATE ON public.equipment_reports
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_if_changed();

DROP TRIGGER IF EXISTS trg_customer_prev_report_updated_at ON public.customer_prev_report;
CREATE TRIGGER trg_customer_prev_report_updated_at
BEFORE UPDATE ON public.customer_prev_report
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_if_changed();

-- ───────────────────────────────────────────────
-- refresh_tokens
-- ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.refresh_tokens (
    id          BIGSERIAL PRIMARY KEY,
    user_id     UUID NOT NULL
                REFERENCES public.doctor_user(id)
                ON DELETE CASCADE,
    jti         TEXT UNIQUE NOT NULL,
    token_hash  TEXT NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked     BOOLEAN NOT NULL DEFAULT false,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE IF NOT EXISTS public.disease_group (
    group_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name TEXT NOT NULL UNIQUE,
    icd_code   TEXT
);

-- Эхний өгөгдөл оруулах
INSERT INTO public.disease_group (group_name, icd_code)
VALUES 
    ('Амьсгал', 'J00–J99'),
    ('Зүрх судас', 'I00–I99'),
    ('Хоол боловсруулах', 'K00–K93'),
    ('Бөөр, шээсний зам', 'N00–N99'),
    ('Дотоод шүүрэл', 'E00–E90'),
    ('Мэс засал', 'ICD-10-PCS'), -- процедурын кодчилол
    ('Гэмтэл', 'S00–T98'),
    ('Эмэгтэйчүүд', 'N70–N98'),
    ('Мэдрэл', 'G00–G99'),
    ('Сэтгэц', 'F00–F99'),
    ('Нүд', 'H00–H59'),
    ('Чих, хамар, хоолой', 'H60–H95'),
    ('Хавдар (хортой)', 'C00–C97'),
    ('Хавдар (хоргүй, тодорхойгүй)', 'D00–D48'),
    ('Арьс, харшил', 'L00–L99'),
    ('Яс, булчин, холбогч эд', 'M00–M99')
ON CONFLICT (group_name) DO NOTHING;


CREATE TABLE IF NOT EXISTS public.customer_disease_report (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    custom_id          INT NOT NULL
                       REFERENCES public.customer_user(id)
                       ON UPDATE CASCADE ON DELETE CASCADE,

    created_doc_id     BIGINT NOT NULL
                       REFERENCES public.doctor_user(doctor_id)
                       ON UPDATE CASCADE ON DELETE SET NULL,

    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    created_org_id     INT,

    customer_report_id BIGINT NOT NULL
                       REFERENCES public.customer_user(disease_report_id)
                       ON UPDATE CASCADE ON DELETE CASCADE,

    disease_type_id    INT NOT NULL
                       REFERENCES public.disease_type(disease_id)
                       ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE OR REPLACE FUNCTION set_customer_disease_report_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_customer_disease_report_updated
BEFORE UPDATE ON public.customer_disease_report
FOR EACH ROW
EXECUTE FUNCTION set_customer_disease_report_updated_at();
